import type { Metadata } from "next";
import { Urbanist, Figtree } from "next/font/google";
import "@/styles/globals.css";
import SalesBanner from "@/components/sales-banner";
import Header from "@/components/header";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

export const metadata: Metadata = {
  title: "Fametonic - Landing",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} ${figtree.variable} antialiased`}
    >
      <body className={`${figtree.variable} antialiased`}>
        <SalesBanner />
        <Header />
        {children}
      </body>
    </html>
  );
}
