import type { Metadata } from "next";
import { Urbanist, Figtree } from "next/font/google";
import "@/styles/globals.css";
import SalesBanner from "@/components/sales-banner";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

export const metadata: Metadata = {
  title: "Fametonic - Landing",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} ${figtree.variable} antialiased`}>
        <SalesBanner />
        {children}
      </body>
    </html>
  );
}
